options:
  logging: CLOUD_LOGGING_ONLY

steps:

# Backend
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/netflix-repo/backend:$SHORT_SHA
  - ./backend

- name: gcr.io/cloud-builders/docker
  args:
  - push
  - us-central1-docker.pkg.dev/$PROJECT_ID/netflix-repo/backend:$SHORT_SHA

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - netflix-backend
  - --image=us-central1-docker.pkg.dev/$PROJECT_ID/netflix-repo/backend:$SHORT_SHA
  - --region=us-central1
  - --platform=managed
  - --allow-unauthenticated
  - --set-secrets=DB_PASSWORD=db-password:latest
  - --set-env-vars=DB_HOST=PRIVATE_IP,DB_USER=netflixuser,DB_NAME=netflixdb
  - --vpc-connector=netflix-connector

# Frontend
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/netflix-repo/frontend:$SHORT_SHA
  - --build-arg
  - REACT_APP_API=https://netflix-backend-xxxxx.a.run.app
  - ./frontend

- name: gcr.io/cloud-builders/docker
  args:
  - push
  - us-central1-docker.pkg.dev/$PROJECT_ID/netflix-repo/frontend:$SHORT_SHA

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - netflix-frontend
  - --image=us-central1-docker.pkg.dev/$PROJECT_ID/netflix-repo/frontend:$SHORT_SHA
  - --region=us-central1
  - --platform=managed
  - --allow-unauthenticated
