steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/app-repo/app:latest',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/app-repo/app:latest'
    ]

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - ssh
  - app-server
  - --zone=asia-south1-a
  - --internal-ip
  - --command
  - |
    docker pull asia-south1-docker.pkg.dev/$PROJECT_ID/app-repo/app:latest &&
    docker stop app || true &&
    docker rm app || true &&
    docker run -d -p 3000:3000 --name app asia-south1-docker.pkg.dev/$PROJECT_ID/app-repo/app:latest

options:
  logging: CLOUD_LOGGING_ONLY

