steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/app:latest',
      '.'
    ]

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/app:latest'
    ]

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - compute
  - ssh
  - app-server
  - --zone=us-central1
  - --internal-ip
  - --command
  - |
    docker pull us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/app:latest &&
    docker stop app || true &&
    docker rm app || true &&
    docker run -d -p 3000:3000 --name app us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/app:latest

options:
  logging: CLOUD_LOGGING_ONLY

