options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _SERVICE: netflix-backend
  _CONNECTOR: netflix-connector
  _DB_HOST: 10.184.192.3
  _DB_USER: netflixuser
  _DB_NAME: netflixdb

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
      env: DB_PASSWORD

steps:

# Build
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/backend:$SHORT_SHA
    - ./backend

# Push
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/backend:$SHORT_SHA

# Deploy
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  secretEnv: ['DB_PASSWORD']
  args:
    - run
    - deploy
    - $_SERVICE
    - --image=us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/backend:$SHORT_SHA
    - --region=$_REGION
    - --platform=managed
    - --allow-unauthenticated
    - --service-account=svc-devops@$PROJECT_ID.iam.gserviceaccount.com
    - --set-secrets=DB_PASSWORD=db-password:latest
    - --set-env-vars=DB_HOST=$_DB_HOST,DB_USER=$_DB_USER,DB_NAME=$_DB_NAME
    - --vpc-connector=$_CONNECTOR
