options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: us-central1
  _BACKEND_SERVICE: netflix-backend
  _FRONTEND_SERVICE: netflix-frontend
  _BACKEND_URL: ""  # Custom substitution for backend URL

steps:

# Backend pipeline
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Backend Pipeline'
  entrypoint: bash
  args:
    - -c
    - |
      echo "Checking backend changes..."
      if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep '^backend/' >/dev/null; then
        echo "Building backend..."
        docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/backend:$SHORT_SHA ./backend
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/backend:$SHORT_SHA
        gcloud run deploy $_BACKEND_SERVICE \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/backend:$SHORT_SHA \
          --region=$_REGION \
          --platform=managed \
          --allow-unauthenticated
      else
        echo "No backend changes. Skipping backend pipeline."
      fi

# Frontend pipeline
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Frontend Pipeline'
  entrypoint: bash
  args:
    - -c
    - |
      echo "Checking frontend changes..."
      if git diff --name-only $COMMIT_SHA^ $COMMIT_SHA | grep '^frontend/' >/dev/null; then
        echo "Building frontend..."
        docker build \
          --build-arg REACT_APP_API=$_BACKEND_URL \
          -t us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/frontend:$SHORT_SHA ./frontend
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/frontend:$SHORT_SHA
        gcloud run deploy $_FRONTEND_SERVICE \
          --image=us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/frontend:$SHORT_SHA \
          --region=$_REGION \
          --platform=managed \
          --allow-unauthenticated
      else
        echo "No frontend changes. Skipping frontend pipeline."
      fi
