options:
  logging: CLOUD_LOGGING_ONLY

steps:

- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/frontend:$SHORT_SHA
  - --build-arg
  - REACT_APP_API=https://netflix-backend-1079769889292.us-central1.run.app
  - ./frontend

- name: gcr.io/cloud-builders/docker
  args:
  - push
  - us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/frontend:$SHORT_SHA

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - netflix-frontend
  - --image=us-central1-docker.pkg.dev/$PROJECT_ID/app-repo/frontend:$SHORT_SHA
  - --region=us-central1
  - --platform=managed
  - --allow-unauthenticated
